
services:
  postgresdb:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_DB: swift_db
      POSTGRES_USER: swift_user
      POSTGRES_PASSWORD: swift_pass
    ports:
      - "5432:5432"
    networks:
      - swift-network

  app:
    build: .
    container_name: swift_app
    ports:
      - "8080:8080"
    depends_on:
      - postgresdb
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresdb:5432/swift_db
      SPRING_DATASOURCE_USERNAME: swift_user
      SPRING_DATASOURCE_PASSWORD: swift_pass
    networks:
      - swift-network

networks:
  swift-network:
